import Mathlib.Data.List.Basic
import Mathlib.Data.Nat.Basic

-- Sequence length
def N : Nat := 2048

-- A "distance" d is reachable in k hops from offset set O if d can be
-- written as a sum of exactly k elements of O (with repetition allowed).
-- Equivalently: BFS from 0 over the additive monoid generated by O.
def reachableInHops (offsets : List Nat) (d : Nat) (maxHops : Nat) : Bool :=
  let rec go (frontier : List Nat) (visited : List Nat) (hopsLeft : Nat) : Bool :=
    if hopsLeft == 0 then frontier.contains d
    else
      let next := frontier.bind (fun x => offsets.map (fun o => x + o))
        |>.filter (fun x => x <= d && !visited.contains x)
        |>.eraseDups
      if next.contains d then true
      else go next (visited ++ next) (hopsLeft - 1)
  go [0] [0] maxHops

-- J12 offset set (prior design)
def j12_offsets : List Nat := [1, 2, 4, 8, 16, 64, 96, 192, 384, 512, 768, 1024]

-- J13D offset set (new design)
def j13d_offsets : List Nat := [1, 2, 4, 5, 8, 16, 32, 64, 128, 256, 512, 768, 1024]

-- Passkey distances
def passkey_distances : List Nat := [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 1536]

-- Passkey gaps (d + 5)
def passkey_gaps : List Nat := passkey_distances.map (· + 5)

-- Simple test
example : reachableInHops j12_offsets 7 2 = false := by decide
