import Mathlib.Data.List.Basic
import Mathlib.Data.Nat.Basic

-- Sequence length
def N : Nat := 2048

-- A "distance" d is reachable in k hops from offset set O if d can be
-- written as a sum of exactly k elements of O (with repetition allowed).
-- Equivalently: BFS from 0 over the additive monoid generated by O.
def reachableInHops (offsets : List Nat) (d : Nat) (maxHops : Nat) : Bool :=
  let rec go (frontier : List Nat) (visited : List Nat) (hopsLeft : Nat) : Bool :=
    if hopsLeft == 0 then frontier.contains d
    else
      let next := frontier.flatMap (fun x => offsets.map (fun o => x + o))
        |>.filter (fun x => x <= d && !visited.contains x)
        |>.eraseDups
      if next.contains d then true
      else go next (visited ++ next) (hopsLeft - 1)
  go [0] [0] maxHops

-- Helper function to compute minimum hops using BFS
def minHops (offsets : List Nat) (d : Nat) : Option Nat :=
  let rec go (frontier : List Nat) (visited : List Nat) (hops : Nat) : Option Nat :=
    if frontier.contains d then some hops
    else if frontier.isEmpty then none
    else 
      let next := frontier.flatMap (fun x => offsets.map (fun o => x + o))
        |>.filter (fun x => x <= d && !visited.contains x)
        |>.eraseDups
      go next (visited ++ next) (hops + 1)
  go [0] [0] 0

-- Helper: Check if a distance is reachable within max hops
-- Using native_decide is preferred for computational proofs
def reachableWithinHops (offsets : List Nat) (d : Nat) (maxHops : Nat) : Bool :=
  match minHops offsets d with
  | some h => h <= maxHops
  | none => false

-- ============================================================================
-- DWARF Paper: Staged Bottleneck Removal - condN vs condP
-- ============================================================================

-- condN offset set: (1..=32) ∪ {48, 64, 96, 128, 192, 256, 384, 512, 768, 1024, 1536}
-- Note: In Rust code, this starts from 0, but for our purposes we use 1..=32
def condN_offsets : List Nat := 
  (List.range 1 33) ++ [48, 64, 96, 128, 192, 256, 384, 512, 768, 1024, 1536]

-- condP offset set: (1..=64) ∪ {96, 128, 192, 256, 384, 512, 768, 1024, 1536}
def condP_offsets : List Nat := 
  (List.range 1 65) ++ [96, 128, 192, 256, 384, 512, 768, 1024, 1536]

-- Theorem 1: All lags in [1, 32] are 1-hop reachable from condN (by direct offset).
-- ∀ d ∈ [1,32], d ∈ condN_offsets.
theorem condN_local_saturation :
    ∀ d : Nat, d ∈ List.range 1 33 → d ∈ condN_offsets := by
  intro d hd
  simp [condN_offsets, List.mem_range] at hd ⊢
  cases hd with
  | intro h1 h2 =>
    interval_cases d <;> decide

-- Theorem 2: The lags [33, 47] require exactly 2 hops from condN.
-- (No direct offset covers them; but 1+32=33, 2+32=34, etc. provide 2-hop paths)
-- ∀ d ∈ [33,47], minHops(condN, d) = 2.
theorem condN_mid_gap :
    ∀ d : Nat, d ∈ List.range 33 48 → 
      (reachableInHops condN_offsets d 2 = true ∧ 
       reachableInHops condN_offsets d 1 = false) := by
  intro d hd
  simp [List.mem_range, reachableInHops, condN_offsets] at hd ⊢
  cases hd with
  | intro h1 h2 =>
    interval_cases d <;> decide

-- Theorem 3: All lags in [1, 64] are 1-hop reachable from condP.
-- ∀ d ∈ [1,64], d ∈ condP_offsets.
theorem condP_extended_saturation :
    ∀ d : Nat, d ∈ List.range 1 65 → d ∈ condP_offsets := by
  intro d hd
  simp [condP_offsets, List.mem_range] at hd ⊢
  cases hd with
  | intro h1 h2 =>
    interval_cases d <;> decide

-- Helper: Count how many lags in [1, N-1] are reachable within maxHops
def count_reachable (offsets : List Nat) (maxHops : Nat) : Nat :=
  let lags := List.range 1 N
  lags.filter (fun d => reachableInHops offsets d maxHops) |>.length

-- Theorem 4: condP's ≤2-hop coverage strictly exceeds condN's ≤2-hop coverage.
-- count_reachable(condP, 2) > count_reachable(condN, 2)
theorem condN_condP_coverage_improvement :
    count_reachable condP_offsets 2 > count_reachable condN_offsets 2 := by
  simp [count_reachable, reachableInHops, condN_offsets, condP_offsets]
  decide

-- Exploration: Compute and compare coverage for both architectures
-- Run with: lake env lean verification/condn_condp_theorems.lean

-- Helper: Count lags by minimum hop depth
def count_lags_by_min_hops (offsets : List Nat) : List (Nat × Nat) :=
  let lags := List.range 1 N
  let counts := lags.map (fun d => (d, minHops offsets d))
  counts

-- Helper: Get count for specific hop depth
def count_lags_at_hops (offsets : List Nat) (hops : Nat) : Nat :=
  let lags := List.range 1 N
  let counts := lags.map (fun d => minHops offsets d)
  counts.filter (fun mh => match mh with | some h => h = hops | none => false) |>.length

-- Helper: Count lags reachable in exactly hops steps
def count_exact_hops (offsets : List Nat) (hops : Nat) : Nat :=
  let lags := List.range 1 N
  lags.filter (fun d => reachableInHops offsets d hops && !reachableInHops offsets d (hops - 1))
    |>.length

-- Exploration results (these are #eval statements, not theorems)
-- Uncomment to run exploration:
-- #eval count_lags_at_hops condN_offsets 1  -- 1-hop reachable for condN
-- #eval count_lags_at_hops condN_offsets 2  -- 2-hop reachable for condN  
-- #eval count_lags_at_hops condN_offsets 3  -- 3-hop reachable for condN
-- #eval count_lags_at_hops condP_offsets 1  -- 1-hop reachable for condP
-- #eval count_lags_at_hops condP_offsets 2  -- 2-hop reachable for condP
-- #eval count_lags_at_hops condP_offsets 3  -- 3-hop reachable for condP

-- Theorem 6: The offsets [33..47] are NOT in condN but ARE in condP.
-- ∀ d ∈ [33,47], d ∉ condN_offsets ∧ d ∈ condP_offsets.
-- (This directly proves condP fixes the structural bottleneck condN left open)
theorem bottleneck_structural :
    ∀ d : Nat, d ∈ List.range 33 48 → 
      (d ∉ condN_offsets ∧ d ∈ condP_offsets) := by
  intro d hd
  simp [condN_offsets, condP_offsets, List.mem_range] at hd ⊢
  cases hd with
  | intro h1 h2 =>
    interval_cases d <;> decide

-- Helper: Count total unique lags reachable in ≤maxHops
def count_reachable_within (offsets : List Nat) (maxHops : Nat) : Nat :=
  let lags := List.range 1 N
  lags.filter (fun d => reachableWithinHops offsets d maxHops) |>.length
