import Mathlib.Data.List.Basic
import Mathlib.Data.Nat.Basic
import Mathlib.Data.Float.Basic
import Mathlib.Data.Real.Basic

-- Sequence length
def N : Nat := 2048

-- A "distance" d is reachable in k hops from offset set O if d can be
-- written as a sum of exactly k elements of O (with repetition allowed).
-- Equivalently: BFS from 0 over the additive monoid generated by O.
def reachableInHops (offsets : List Nat) (d : Nat) (maxHops : Nat) : Bool :=
  let rec go (frontier : List Nat) (visited : List Nat) (hopsLeft : Nat) : Bool :=
    if hopsLeft == 0 then frontier.contains d
    else
      let next := frontier.flatMap (fun x => offsets.map (fun o => x + o))
        |>.filter (fun x => x <= d && !visited.contains x)
        |>.eraseDups
      if next.contains d then true
      else go next (visited ++ next) (hopsLeft - 1)
  go [0] [0] maxHops

-- J13D offset set (from Prompt 11)
def j13d : List Nat := [1, 2, 4, 5, 8, 16, 32, 64, 128, 256, 512, 768, 1024]

-- J24D offset set (se015)
def j24d : List Nat := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13, 15, 16, 21, 23, 28, 48, 64, 96, 192, 384, 512, 768, 1024]

-- Split each into "local" and "relay" subsets using a boundary offset b
def localOffsets (S : List Nat) (b : Nat) : List Nat := S.filter (· < b)
def relayOffsets (S : List Nat) (b : Nat) : List Nat := S.filter (· ≥ b)

-- ============================================================================
-- Step 1: Characterize both offset sets formally
-- ============================================================================

def j13d_local_32 : List Nat := localOffsets j13d 32
def j13d_relay_32 : List Nat := relayOffsets j13d 32

def j24d_local_48 : List Nat := localOffsets j24d 48
def j24d_relay_48 : List Nat := relayOffsets j24d 48

-- ============================================================================
-- Step 2: Compute cluster statistics
-- ============================================================================

def compute_local_stats (S : List Nat) (b : Nat) : (Float × Float × Float) :=
  let local := localOffsets S b
  let mean := (local.sum.toFloat) / local.length.toFloat
  let density := local.length.toFloat / b.toFloat
  (mean, density, local.length.toFloat)

#eval do
  let (mean13, density13, count13) := compute_local_stats j13d 32
  let (mean24, density24, count24) := compute_local_stats j24d 48
  IO.println s!"J13D local: {j13d_local_32}"
  IO.println s!"J13D local mean = {mean13}, density = {density13}, count = {count13}"
  IO.println s!"J24D local: {j24d_local_48}"
  IO.println s!"J24D local mean = {mean24}, density = {density24}, count = {count24}"

-- Geometric mean helper
def geometric_mean (offsets : List Nat) : Float :=
  if offsets.isEmpty then 0.0
  else
    let log_sum := offsets.map (fun x => Real.log x.toFloat) |>.foldl (· + ·) 0.0
    Real.exp (log_sum / offsets.length.toFloat)

#eval do
  let geo13 := geometric_mean j13d_local_32
  let geo24 := geometric_mean j24d_local_48
  IO.println s!"J13D local geometric mean = {geo13}"
  IO.println s!"J24D local geometric mean = {geo24}"

-- ============================================================================
-- Step 3: Test candidate unified formulas
-- ============================================================================

-- Candidate formulas
def formula_a (local_max relay_min : Nat) : Float := 1.0 / Float.sqrt ((local_max.toFloat * relay_min.toFloat))
def formula_b (relay_min : Nat) : Float := 1.0 / relay_min.toFloat
def formula_c (local_mean relay_min : Nat) : Float := 1.0 / Float.sqrt ((local_mean.toFloat * relay_min.toFloat))
def formula_d (local_geo_mean relay_min : Nat) : Float := 1.0 / Float.sqrt ((local_geo_mean * relay_min.toFloat))
def formula_e (relay_min density : Float) : Float := 1.0 / (relay_min.toFloat * density)
def formula_f (density : Float) : Float := density / 100.0  -- Normalized density
def formula_g (local_max relay_min density_local : Float) : Float :=
  formula_a local_max relay_min / density_local
def formula_h (relay_min count : Nat) : Float := 1.0 / Float.sqrt (count.toFloat * relay_min.toFloat)
def formula_i (count relay_min : Nat) : Float := 1.0 / (Float.sqrt count.toFloat * relay_min.toFloat)
def formula_j (relay_min : Nat) : Float := 1.0 / Float.sqrt (relay_min.toFloat * Float.log2 relay_min.toFloat)

-- Get δ_local_max for boundary b
def get_local_max (S : List Nat) (b : Nat) : Nat :=
  (localOffsets S b).maximum?.getD 0

-- Get δ_relay_min (which is just the boundary)
def get_relay_min (b : Nat) : Nat := b

-- Get local density for boundary b
def get_local_density (S : List Nat) (b : Nat) : Float :=
  let local := localOffsets S b
  local.length.toFloat / b.toFloat

-- Evaluate all formulas
def evaluate_formulas (S : List Nat) (b : Nat) (trained_alpha : Float) : (List (String × Float × Float)) :=
  let local_max := get_local_max S b
  let relay_min := get_relay_min b
  let local_mean := (localOffsets S b).sum.toFloat / (localOffsets S b).length.toFloat
  let local_geo := geometric_mean (localOffsets S b)
  let density := get_local_density S b
  let count := (localOffsets S b).length
  let log2_relay := Float.log2 relay_min.toFloat
  [
    ("(a) 1/√(δ_local_max × δ_relay_min)", formula_a local_max relay_min, trained_alpha),
    ("(b) 1/δ_relay_min", formula_b relay_min, trained_alpha),
    ("(c) 1/√(δ_mean_local × δ_relay_min)", formula_c local_max relay_min, trained_alpha),
    ("(d) 1/√(δ_geometric_mean_local × δ_relay_min)", formula_d local_geo relay_min, trained_alpha),
    ("(e) 1/(δ_relay_min × density_local)", formula_e relay_min density, trained_alpha),
    ("(f) density_local / 100", formula_f density, trained_alpha),
    ("(g) 1/√(δ_local_max × δ_relay_min) × (1/density)", formula_g local_max relay_min density, trained_alpha),
    ("(h) 1/(δ_relay_min × √(J_local))", formula_h relay_min count, trained_alpha),
    ("(i) 1/(√(J_local) × δ_relay_min)", formula_i count relay_min, trained_alpha),
    ("(j) 1/(δ_relay_min × log2(δ_relay_min))", formula_j relay_min, trained_alpha)
  ]

def compute_errors (predictions : List (String × Float × Float)) : List (String × Float × Float × Float) :=
  predictions.map (fun (name, pred, trained) => 
    let error := Float.abs (pred - trained) / trained * 100.0
    (name, pred, trained, error))

def print_results (results : List (String × Float × Float × Float)) (arch_name : String) : IO Unit := do
  IO.println s!"\n{arch_name} RESULTS:"
  IO.println "Formula | Predicted | Trained | Error%"
  IO.println "--------|-----------|---------|-------"
  for (name, pred, trained, error) <- results do
    IO.println s!"{name} | {pred:.6f} | {trained:.4f} | {error:.2f}%"
  
  let total_error := results.map (fun (_, _, _, err) => err) |>.foldl (· + ·) 0.0
  let avg_error := total_error / results.length.toFloat
  IO.println s!"\nAverage error: {avg_error:.2f}%"

-- Main evaluation
#eval do
  -- J13D: trained α = 0.044 (from Prompt 11)
  let j13d_results := compute_errors (evaluate_formulas j13d 32 0.044)
  print_results j13d_results "J13D"
  
  -- J24D: trained α = 0.0207 (from run_gen5_L8_se015.log)
  let j24d_results := compute_errors (evaluate_formulas j24d 48 0.0207)
  print_results j24d_results "J24D"

-- Combined error metric
def combined_error (j13d_results j24d_results : List (String × Float × Float × Float)) : Float :=
  let j13d_errors := j13d_results.map (fun (_, _, _, err) => err)
  let j24d_errors := j24d_results.map (fun (_, _, _, err) => err)
  let total_error := (j13d_errors ++ j24d_errors).foldl (· + ·) 0.0
  total_error / (j13d_errors.length + j24d_errors.length).toFloat

-- Find best formula by combined error
#eval do
  let j13d_results := compute_errors (evaluate_formulas j13d 32 0.044)
  let j24d_results := compute_errors (evaluate_formulas j24d 48 0.0207)
  let best_formula := 
    [("J13D", j13d_results), ("J24D", j24d_results)]
    |>.bind (fun (name, results) => results.map (fun (formula, _, _, _) => (formula, name)))
    |>.foldl (fun best (formula, arch) => 
      let err := match arch with
        | "J13D" => (j13d_results.find? (fun (n, _, _, _) => n == formula)).get!.2.2.2
        | "J24D" => (j24d_results.find? (fun (n, _, _, _) => n == formula)).get!.2.2.2
        | _ => 0.0
      if err < best.2 then (formula, err) else best) ("", Float.inf)
  
  IO.println s!"\nBest formula by combined error: {best_formula.1} (error contribution: {best_formula.2:.2f}%)"
  
  let total_err := combined_error j13d_results j24d_results
  IO.println s!"Combined average error: {total_err:.2f}%"
