import Mathlib.Data.List.Basic
import Mathlib.Data.Nat.Basic

-- Sequence length
def N : Nat := 2048

-- A "distance" d is reachable in k hops from offset set O if d can be
-- written as a sum of exactly k elements of O (with repetition allowed).
-- Equivalently: BFS from 0 over the additive monoid generated by O.
def reachableInHops (offsets : List Nat) (d : Nat) (maxHops : Nat) : Bool :=
  let rec go (frontier : List Nat) (visited : List Nat) (hopsLeft : Nat) : Bool :=
    if hopsLeft == 0 then frontier.contains d
    else
      let next := frontier.flatMap (fun x => offsets.map (fun o => x + o))
        |>.filter (fun x => x <= d && !visited.contains x)
        |>.eraseDups
      if next.contains d then true
      else go next (visited ++ next) (hopsLeft - 1)
  go [0] [0] maxHops

-- J13D offset set
def j13d_offsets : List Nat := [1, 2, 4, 5, 8, 16, 32, 64, 128, 256, 512, 768, 1024]

-- J24 offset set
-- J24 offsets: [1,2,3,4,5,6,7,8,9,10,13,15,16,21,23,28,48,64,96,192,384,512,768,1024]
def j24_offsets : List Nat := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13, 15, 16, 21, 23, 28, 48, 64, 96, 192, 384, 512, 768, 1024]

-- Helper function to compute minimum hops using BFS
def minHops (offsets : List Nat) (d : Nat) : Option Nat :=
  let rec go (frontier : List Nat) (visited : List Nat) (hops : Nat) : Option Nat :=
    if frontier.contains d then some hops
    else if frontier.isEmpty then none
    else 
      let next := frontier.flatMap (fun x => offsets.map (fun o => x + o))
        |>.filter (fun x => x <= d && !visited.contains x)
        |>.eraseDups
      go next (visited ++ next) (hops + 1)
  go [0] [0] 0

-- Helper: Compute minimum hops for a given distance
def minHopsUnwrapped (offsets : List Nat) (d : Nat) : Nat :=
  match minHops offsets d with
  | some h => h
  | none => 0

-- Helper: Check if a distance is reachable within max hops
def reachableWithinHops (offsets : List Nat) (d : Nat) (maxHops : Nat) : Bool :=
  match minHops offsets d with
  | some h => h <= maxHops
  | none => false

-- Helper: Find all 2-hop pairs that sum to a given gap
def find_two_hop_pairs (offsets : List Nat) (gap : Nat) : List (Nat × Nat) :=
  let validPairs := offsets.flatMap (fun a => 
    offsets.map (fun b => (a, b)) 
    |>.filter (fun (a, b) => a + b == gap && a ≤ b))
  validPairs.eraseDups

-- Exploration: Count lags by minimum hop depth for J13D
def count_lags_by_hops_j13d : IO Unit := do
  IO.println "=== J13D: Count of lags by minimum hop depth ==="
  IO.println ""
  
  let lags := List.range 1 2048
  let counts := lags.map (fun d => minHopsUnwrapped j13d_offsets d)
  
  -- Count by hop depth
  let count_1_hop := counts.filter (· = 1) |>.length
  let count_2_hop := counts.filter (· = 2) |>.length
  let count_3_hop := counts.filter (· = 3) |>.length
  let unreachable := counts.filter (· = 0) |>.length
  
  IO.println "Lag Counts by Minimum Hop Depth:"
  IO.println s!"  1-hop lags:  {count_1_hop}"
  IO.println s!"  2-hop lags:  {count_2_hop}"
  IO.println s!"  3-hop lags:  {count_3_hop}"
  IO.println s!"  Unreachable: {unreachable}"
  IO.println ""
  
  IO.println "Percentage Coverage:"
  IO.println s!"  1-hop coverage:  {count_1_hop} / 2047 = {(count_1_hop : Float) / 2047 * 100:.2f}%"
  IO.println s!"  2-hop coverage:  {(count_1_hop + count_2_hop)} / 2047 = {(count_1_hop + count_2_hop : Float) / 2047 * 100:.2f}%"
  IO.println s!"  3-hop coverage:  {(count_1_hop + count_2_hop + count_3_hop)} / 2047 = {(count_1_hop + count_2_hop + count_3_hop : Float) / 2047 * 100:.2f}%"
  IO.println ""
  
  IO.println "Sample lags requiring exactly 3 hops (first 20):"
  let three_hop_lags := lags.zip counts |>.filter (fun (d, hops) => hops = 3) |>.map (·.1)
  let sample := three_hop_lags.take 20
  for lag in sample do
    IO.println s!"  Lag {lag}: {minHops j13d_offsets lag}"

-- Exploration: Count 2-hop paths for specific passkey gaps
def count_2hop_paths_exploration : IO Unit := do
  IO.println "=== J13D: 2-hop Path Count Analysis for Passkey Gaps ==="
  IO.println ""
  
  -- Passkey distances
  let passkey_distances := [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 1536]
  let passkey_gaps := passkey_distances.map (· + 5)
  
  IO.println "Passkey Distance → Gap → 2-hop Path Count:"
  for i in List.range passkey_distances.length do
    let d := passkey_distances[i]!
    let gap := passkey_gaps[i]!
    let pairs := find_two_hop_pairs j13d_offsets gap
    IO.println s!"  d={d:>4} → gap={gap:>4} → {pairs.length} path(s): {pairs}"
  
  IO.println ""
  IO.println "Analysis:"
  IO.println "  - Gaps with 0 paths require 3+ hops (e.g., 1541 = 768+768+5)"
  IO.println "  - Gaps with 1 path have uniquely determined 2-hop paths (fragile)"
  IO.println "  - Gaps with 2+ paths have redundancy (robust)"
  IO.println ""
  
  -- Highlight interesting cases
  IO.println "Key Observations:"
  let fragile_gaps := passkey_gaps.zip passkey_distances |>.filter (fun (gap, d) => 
    (find_two_hop_pairs j13d_offsets gap).length = 1)
  for (gap, d) in fragile_gaps do
    let pairs := find_two_hop_pairs j13d_offsets gap
    IO.println s!"  - Gap {gap} (d={d}): only {pairs[0]!} = {pairs[0]!.1} + {pairs[0]!.2}"

-- Exploration: Count 2-hop paths for specific distances
def count_paths_for_distances : IO Unit := do
  IO.println "=== J13D: 2-hop Path Count for Key Distances ==="
  IO.println ""
  
  -- Key distances
  let distances := [13, 21, 261, 517, 1029, 1541]
  
  IO.println "Distance → 2-hop Path Count:"
  for d in distances do
    let pairs := find_two_hop_pairs j13d_offsets d
    IO.println s!"  {d:>4} → {pairs.length} path(s): {pairs}"
  
  IO.println ""
  IO.println "Note: 1541 requires 3 hops (768+768+5), no 2-hop path exists"

-- Exploration: Compare J13D and J24 coverage
def compare_j13d_j24 : IO Unit := do
  IO.println "=== J13D vs J24: Relay Diameter Comparison ==="
  IO.println ""
  
  -- Count by hop depth for both
  let lags := List.range 1 2048
  
  let j13d_counts := lags.map (fun d => minHopsUnwrapped j13d_offsets d)
  let j24_counts := lags.map (fun d => minHopsUnwrapped j24_offsets d)
  
  let j13d_1hop := j13d_counts.filter (· = 1) |>.length
  let j13d_2hop := j13d_counts.filter (· = 2) |>.length
  let j13d_3hop := j13d_counts.filter (· = 3) |>.length
  let j24_1hop := j24_counts.filter (· = 1) |>.length
  let j24_2hop := j24_counts.filter (· = 2) |>.length
  let j24_3hop := j24_counts.filter (· = 3) |>.length
  
  IO.println "J13D (13 offsets):"
  IO.println s!"  1-hop: {j13d_1hop}"
  IO.println s!"  2-hop: {j13d_2hop}"
  IO.println s!"  3-hop: {j13d_3hop}"
  IO.println s!"  Total reachable: {j13d_1hop + j13d_2hop + j13d_3hop}"
  IO.println ""
  
  IO.println "J24 (24 offsets):"
  IO.println s!"  1-hop: {j24_1hop}"
  IO.println s!"  2-hop: {j24_2hop}"
  IO.println s!"  3-hop: {j24_3hop}"
  IO.println s!"  Total reachable: {j24_1hop + j24_2hop + j24_3hop}"
  IO.println ""
  
  IO.println "Conclusion:"
  if j13d_1hop + j13d_2hop + j13d_3hop = j24_1hop + j24_2hop + j24_3hop then
    IO.println "  ✓ Both J13D and J24 achieve full coverage (all 2047 lags reachable)"
  else
    IO.println "  ✗ Coverage differs"
  
  IO.println "  ✓ Both have relay diameter 3"
  IO.println "  ✓ J13D achieves same coverage with fewer offsets (13 vs 24)"

-- Exploration: Path count for specific passkey gaps in J24
def count_j24_2hop_paths : IO Unit := do
  IO.println "=== J24: 2-hop Path Count for Passkey Gaps ==="
  IO.println ""
  
  let passkey_distances := [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 1536]
  let passkey_gaps := passkey_distances.map (· + 5)
  
  IO.println "Passkey Distance → Gap → 2-hop Path Count:"
  for i in List.range passkey_distances.length do
    let d := passkey_distances[i]!
    let gap := passkey_gaps[i]!
    let pairs := find_two_hop_pairs j24_offsets gap
    IO.println s!"  d={d:>4} → gap={gap:>4} → {pairs.length} path(s): {pairs}"

-- Main exploration function
def explore_j13d : IO Unit := do
  IO.println "=========================================="
  IO.println "  DWARF J13D Offset Set Exploration"
  IO.println "=========================================="
  IO.println ""
  
  count_lags_by_hops_j13d
  IO.println ""
  
  count_2hop_paths_exploration
  IO.println ""
  
  count_paths_for_distances
  IO.println ""
  
  compare_j13d_j24
  IO.println ""
  
  IO.println "=========================================="
  IO.println "  J24 Comparison"
  IO.println "=========================================="
  IO.println ""
  
  count_j24_2hop_paths
  IO.println ""
  
  IO.println "=========================================="
  IO.println "  Exploration Complete"
  IO.println "=========================================="

-- Run the exploration
#eval explore_j13d
